# This file was generated by GoReleaser. DO NOT EDIT.
class ClusterCaution < Formula
  desc "Prevents execution errors in kubectl"
  homepage "https://github.com/pyama86/cluster-caution"
  url "https://github.com/pyama86/cluster-caution/releases/download/0.1.1/cluster-caution_0.1.1_darwin_amd64.tar.gz"
  version "0.1.1"
  sha256 "50adc908ec7f28aecae7877cac8643b9d0c0f6cafdd9cbc6acd442c0b630876d"

  def install
    bin.install 'kubectl-cluster-caution'
  end

  test do
    system "#{bin}/kubectl-cluster-caution"
  end
end
