# This file was generated by GoReleaser. DO NOT EDIT.
class ClusterCaution < Formula
  desc "Prevents execution errors in kubectl"
  homepage "https://github.com/pyama86/cluster-caution"
  url "https://github.com/pyama86/cluster-caution/releases/download/0.1.2/cluster-caution_0.1.2_darwin_amd64.tar.gz"
  version "0.1.2"
  sha256 "7d3ab349f12812f70bf3ab2a59b12754a00478f9f03d8ec0cae9fa22b3390bfc"

  def install
    bin.install 'kubectl-cluster-caution'
  end

  test do
    system "#{bin}/kubectl-cluster-caution"
  end
end
