# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pachanger < Formula
  desc "pachanger is a tool to change the package name of Go source code."
  homepage "https://github.com/pyama86/pachanger"
  version "0.0.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pyama86/pachanger/releases/download/v0.0.10/pachanger_0.0.10_darwin_amd64.tar.gz"
      sha256 "f451eef9577fdf9fdff590170158ddc7badc4cd8f21bdec4868e8258ab1d041b"

      def install
        bin.install Dir['pachanger']
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pyama86/pachanger/releases/download/v0.0.10/pachanger_0.0.10_darwin_arm64.tar.gz"
      sha256 "252549bf16ab12dcbc6f6f31f58841a63f0f57423f177b7866f056fabdaf3998"

      def install
        bin.install Dir['pachanger']
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pyama86/pachanger/releases/download/v0.0.10/pachanger_0.0.10_linux_amd64.tar.gz"
        sha256 "54c1bd69ac9afa3a51fb71b712a856f82b485e8ce2797874435e33f30de0728e"

        def install
          bin.install Dir['pachanger']
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pyama86/pachanger/releases/download/v0.0.10/pachanger_0.0.10_linux_arm64.tar.gz"
        sha256 "dfde3f203fab52cf9096032a831a38dc24ce4564764e168016bec423d20ac384"

        def install
          bin.install Dir['pachanger']
        end
      end
    end
  end

  test do
    system "#{bin}/pachanger"
  end
end
