# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pdr < Formula
  desc "docker-compose cli wrapper"
  homepage "https://github.com/pyama86/pdr"
  version "0.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/pyama86/pdr/releases/download/v0.0.1/pdr_0.0.1_darwin_amd64.tar.gz"
    sha256 "ccc6b23afc6fb6eb62036baf0b9d25ca6acb1396f3242024d0fd15e4e7af7cd6"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/pyama86/pdr/releases/download/v0.0.1/pdr_0.0.1_linux_amd64.tar.gz"
    sha256 "483969bf82cf68bd0c2338dbd0f2605b1789c8e9d480ffb2fa0c4a5d774a26f5"
  end

  def install
    bin.install Dir['pdr']
  end

  test do
    system "#{bin}/pdr"
  end
end
