# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pdr < Formula
  desc "docker-compose cli wrapper"
  homepage "https://github.com/pyama86/pdr"
  version "0.0.3"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/pyama86/pdr/releases/download/v0.0.3/pdr_0.0.3_darwin_amd64.tar.gz"
    sha256 "93b95a9386dce8df9831b0de8ad374eb19d8d751652e02cc43d79636d529f72d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/pyama86/pdr/releases/download/v0.0.3/pdr_0.0.3_linux_amd64.tar.gz"
    sha256 "9f43d3c5065cfc58cfbcc54f68d45aa80aabf1a1c0e1686b910820d770db1420"
  end

  def install
    bin.install Dir['pdr']
  end

  test do
    system "#{bin}/pdr"
  end
end
