# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedisSweeper < Formula
  desc "redis-sweeper is a tool to delete keys from redis."
  homepage "https://github.com/pyama86/redis-sweeper"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pyama86/redis-sweeper/releases/download/v0.0.2/redis-sweeper_0.0.2_darwin_amd64.tar.gz"
      sha256 "beb91a86386f30935714f4925980a7a9a7defc0a025883954e70315736406f4c"

      def install
        bin.install Dir['redis-sweeper']
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pyama86/redis-sweeper/releases/download/v0.0.2/redis-sweeper_0.0.2_darwin_arm64.tar.gz"
      sha256 "086b2e452fa6b017a6a7e007ed2f0771075db676874c6a2d5d4af4d3121ea480"

      def install
        bin.install Dir['redis-sweeper']
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pyama86/redis-sweeper/releases/download/v0.0.2/redis-sweeper_0.0.2_linux_amd64.tar.gz"
        sha256 "702ed07f84ac78142f0236d78664a990fe65540d17a73efe5dad2b27c81cd646"

        def install
          bin.install Dir['redis-sweeper']
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pyama86/redis-sweeper/releases/download/v0.0.2/redis-sweeper_0.0.2_linux_arm64.tar.gz"
        sha256 "6054f82b7a20725b987d6254448280b807372de8d960505dc311508efa778d60"

        def install
          bin.install Dir['redis-sweeper']
        end
      end
    end
  end

  test do
    system "#{bin}/redis-sweeper"
  end
end
