# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TtyShare < Formula
  desc "tty share to somebody"
  homepage "https://github.com/pyama86/tty-share"
  version "2.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pyama86/tty-share/releases/download/v2.4.0/tty-share_2.4.0_darwin_arm64.tar.gz"
      sha256 "0e547ba8e2f19504b8038cccd64de9ac3a21e4e9eab21afd536bd81f0a52e497"

      def install
        bin.install 'tty-share'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pyama86/tty-share/releases/download/v2.4.0/tty-share_2.4.0_darwin_amd64.tar.gz"
      sha256 "6bb6a665f409df4fb07f4e5999d1d1fb93259f4e67871c4d5d197a6b6e200d2c"

      def install
        bin.install 'tty-share'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pyama86/tty-share/releases/download/v2.4.0/tty-share_2.4.0_linux_amd64.tar.gz"
      sha256 "7e9acf8585525e28bc41b249489322397c9ca6684b3390dc199dbfddbd58aecc"

      def install
        bin.install 'tty-share'
      end
    end
  end

  test do
    system "#{bin}/tty-share"
  end
end
