# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TtyShare < Formula
  desc "tty share to somebody"
  homepage "https://github.com/pyama86/tty-share"
  version "2.4.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pyama86/tty-share/releases/download/v2.4.3/tty-share_2.4.3_darwin_arm64.tar.gz"
      sha256 "8e6526b2059774618479ac625c31e7eef01b59792b79a6477f04b2e538409568"

      def install
        bin.install 'tty-share'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pyama86/tty-share/releases/download/v2.4.3/tty-share_2.4.3_darwin_amd64.tar.gz"
      sha256 "225d3d2b4504dbfabd5ad8f43b89e269c69a2436424d65b8ccafe0f42f3843b6"

      def install
        bin.install 'tty-share'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pyama86/tty-share/releases/download/v2.4.3/tty-share_2.4.3_linux_amd64.tar.gz"
      sha256 "d38aecf1f3f1e5289b75c64963ec469504fac4c8fa5871eb98d4d1e806bbab48"

      def install
        bin.install 'tty-share'
      end
    end
  end

  test do
    system "#{bin}/tty-share"
  end
end
